import { useState } from 'react';
import { MainLayout } from '@/components/layout/MainLayout';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { CreateProductModal } from '@/components/products/CreateProductModal';
import { ManageCategoriesModal } from '@/components/products/ManageCategoriesModal';
import { useProducts } from '@/hooks/useProducts';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { MoreVertical, Search, Plus, Tags, Package, Upload } from 'lucide-react';
import { DEFAULT_CATEGORIES } from '@/constants/data';

export default function Products() {
  const [searchTerm, setSearchTerm] = useState('');
  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false);
  const [isCategoriesModalOpen, setIsCategoriesModalOpen] = useState(false);
  // const [isImportModalOpen, setIsImportModalOpen] = useState(false); // Unused for now
  
  // Local state for categories until we have a backend table
  const [categories, setCategories] = useState(DEFAULT_CATEGORIES);

  const { products, isLoading, deleteProduct, createProduct, updateProduct } = useProducts();
  const [productToEdit, setProductToEdit] = useState<any>(null);

  const filteredProducts = products.filter((product) =>
    product.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
    product.sku.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const handleCreateProduct = (productData: any) => {
      // Remove ID as it is generated by backend, AND additionalBarcodes as it's not in schema yet
      const { id, additionalBarcodes, ...newProduct } = productData;
      createProduct.mutate(newProduct);
  };

  const handleUpdateProduct = (productData: any) => {
      updateProduct.mutate(productData);
  };

  const handleDuplicateProduct = (product: any) => {
      const { id, ...productData } = product;
      createProduct.mutate({
          ...productData,
          name: `${productData.name} (Copia)`,
          sku: `${productData.sku}-COPY`
      });
  };

  const openCreateModal = () => {
      setProductToEdit(null);
      setIsCreateModalOpen(true);
  };

  return (
    <MainLayout title="Productos" subtitle="Gestiona tu inventario">
      <div className="flex flex-col gap-6">
        {/* Actions Bar */}
        <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div className="relative flex-1 sm:max-w-md">
            <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
            <Input
              placeholder="Buscar por nombre o SKU..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="pl-10"
            />
          </div>
          <div className="flex gap-2">
            <Button variant="outline" onClick={() => setIsCategoriesModalOpen(true)}>
              <Tags className="mr-2 h-4 w-4" />
              Categorías
            </Button>
            {/* Removed Import Button for now to clean up, or disable it */}
            <Button variant="outline" disabled>
              <Upload className="mr-2 h-4 w-4" />
              Importar
            </Button>
            <Button onClick={openCreateModal} className="gradient-primary text-primary-foreground shadow-orange">
              <Plus className="mr-2 h-4 w-4" />
              Nuevo Producto
            </Button>
          </div>
        </div>

        {/* Products Table */}
        <div className="rounded-2xl border bg-card shadow-sm overflow-hidden">
          <Table>
            <TableHeader>
              <TableRow className="bg-muted/50 hover:bg-muted/50">
                <TableHead>Producto</TableHead>
                <TableHead>Categoría</TableHead>
                <TableHead>SKU</TableHead>
                <TableHead className="text-right">Precio</TableHead>
                <TableHead className="w-[50px]"></TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {isLoading ? (
                <TableRow>
                  <TableCell colSpan={5} className="text-center py-8 text-muted-foreground">
                    Cargando productos...
                  </TableCell>
                </TableRow>
              ) : filteredProducts.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={5} className="text-center py-8 text-muted-foreground">
                    No se encontraron productos
                  </TableCell>
                </TableRow>
              ) : (
                filteredProducts.map((product) => (
                  <TableRow key={product.id} className="group hover:bg-muted/50 transition-colors">
                    <TableCell>
                      <div>
                        <p className="font-medium text-foreground">{product.name}</p>
                        <p className="text-sm text-muted-foreground">
                          {product.description}
                        </p>
                      </div>
                    </TableCell>
                    <TableCell>
                      <span className="inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 border-transparent bg-secondary text-secondary-foreground hover:bg-secondary/80">
                        {product.category}
                      </span>
                    </TableCell>
                    <TableCell className="font-mono text-sm">{product.sku}</TableCell>
                    <TableCell className="text-right font-medium">
                      S/ {product.price.toFixed(2)}
                    </TableCell>
                    <TableCell>
                      <DropdownMenu>
                        <DropdownMenuTrigger asChild>
                          <Button variant="ghost" size="icon" className="h-8 w-8 opacity-0 group-hover:opacity-100 transition-opacity">
                            <MoreVertical className="h-4 w-4" />
                          </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align="end">
                          <DropdownMenuItem onClick={() => {
                              setProductToEdit(product);
                              setIsCreateModalOpen(true);
                          }}>
                            Editar
                          </DropdownMenuItem>
                          <DropdownMenuItem onClick={() => handleDuplicateProduct(product)}>
                            Duplicar
                          </DropdownMenuItem>
                          <DropdownMenuItem 
                              className="text-destructive focus:text-destructive"
                              onClick={() => deleteProduct.mutate(product.id)}
                          >
                            Eliminar
                          </DropdownMenuItem>
                        </DropdownMenuContent>
                      </DropdownMenu>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </div>
      </div>

      {filteredProducts.length === 0 && !isLoading && (
        <div className="mt-12 text-center">
          <Package className="mx-auto h-12 w-12 text-muted-foreground/50" />
          <h3 className="mt-4 text-lg font-medium text-foreground">
            No se encontraron productos
          </h3>
          <p className="mt-2 text-sm text-muted-foreground">
            Intenta ajustar los filtros de búsqueda
          </p>
        </div>
      )}

      <CreateProductModal
        open={isCreateModalOpen}
        onOpenChange={setIsCreateModalOpen}
        categories={categories}
        onProductCreated={handleCreateProduct}
        productToEdit={productToEdit}
        onProductUpdated={handleUpdateProduct}
      />
      
      <ManageCategoriesModal
        open={isCategoriesModalOpen}
        onOpenChange={setIsCategoriesModalOpen}
        categories={categories}
        onUpdateCategories={setCategories}
      />
    </MainLayout>
  );
}
